### ISSUE TITLE
JPEG contains garbge bytes

### ISSUE THREAD

**Issue by hgourvest** [xiaozhuai/imageinfo#4]
![Yakari T01-0000](https://github.com/xiaozhuai/imageinfo/assets/1659652/5f4481ce-4854-40cb-b328-ce0fcbd97490)
in this jpeg file, there's a section with comment text (FF FE) of size 3 bytes, unfortunately, it seems that the minimum size of a section is 4 bytes, so the next iteration moves the cursor to the wrong place.

**Comment by xiaozhuai** [comment]
Em...I looked into it and found something.
You can insert any bytes between sections. It won't damage jpg. Here I insert 7 bytes `0A`.
<img width="382" alt="image" src="https://github.com/xiaozhuai/imageinfo/assets/4773701/83b2cc50-3535-4f07-892b-96eabbaf608e">

Since every section start with `FF`, so the correct way may be skipping the garbge bytes.

What's your suggestion?

**Comment by xiaozhuai** [comment]
![image](https://github.com/xiaozhuai/imageinfo/assets/4773701/2c494ddf-14b9-4d71-9355-df3eaf8d06a2)
And I looked into 010 editor's template code. It also treat these bytes as garbge and just skip them.
I'll fix this soon.

**Comment by xiaozhuai** [comment]
Fix in https://github.com/xiaozhuai/imageinfo/commit/8f94e1f68d6b40a535090aac696be7a43cc1df61
Thanks for reporting this.

**Comment by xiaozhuai** [comment]
@hgourvest 
Since this issue is solved, I'm going to close it as completed.
Feel free to reopen if you'd like to discuss further.

**Comment by hgourvest** [comment]
Thank you very much for the quick fix. I appreciate your work.
